# Rendimientos

In [1]:
import pandas as pd
import yfinance as yf
import numpy as np

# definimos dataframe

df = yf.download(
    'TSLA' , # ticker
    start = '2010-01-01' , # fecha de entrada
    end = '2024-06-17' , # fecha de salida
    progress= False )  # progreso

df = df.loc[:,['Adj Close']] # con esto obtengo solo la columna adj close
df = df.loc["2020-05-05":,['Adj Close']] # con esto obtengo todos los adj close a partir de dicha fecha
df.rename(columns = {'Adj Close' : 'adj_close'} , inplace = True) # cambiamos el nombre de la columna adj close para evitar confusiones con los espacios
# Calculamos los rendimientos simples y logaritmicos

df['rendimiento_simple'] = df.adj_close.pct_change() # calculamos el rendimiento simple con la funcion pct_change()


df['rendimiento_logaritmico'] = np.log(df.adj_close/df.adj_close.shift(1)) # calculamos el rendimiento logartimico con el logaritmo de la division de los adj close

df

             adj_close  rendimiento_simple  rendimiento_logaritmico
Date
2020-05-05   51.214001                 NaN                      NaN
2020-05-06   52.172001            0.018706                 0.018533
2020-05-07   52.002666           -0.003246                -0.003251
2020-05-08   54.627998            0.050485                 0.049252
2020-05-11   54.085999           -0.009922                -0.009971
...                ...                 ...                      ...
2024-06-10  173.789993           -0.020791                -0.021010
2024-06-11  170.660004           -0.018010                -0.018174
2024-06-12  177.289993            0.038849                 0.038113
2024-06-13  182.470001            0.029218                 0.028799
2024-06-14  178.009995           -0.024442                -0.024746

[1036 rows x 3 columns]